services:
  db:
    container_name: bango-parc-db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ayuwoki
      POSTGRES_PASSWORD: totoro10
      POSTGRES_DB: bango_parc_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
